version: '3.8'

services:
  backend:
    build:
      context: ./backend-nodejs
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend-nodejs:/app
      - /app/node_modules
    restart: always

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    restart: always

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
